importScripts('./build-assets.js','./sw-integrity.js');
const CACHE_PREFIX='adrian-hub-';
const CACHE='adrian-hub-'+self.AdrianRelease.build;
const SCOPE_PATH=(self.registration?.scope||'/adrian-hub/').replace(/^https?:\/\/[^/]+/,'');
const PAYLOADS='dc-inbox-payloads';
const SHELL=['./garden-cottage.js?v=1.0.0','./apps/biblioteca/task-garden.js','./version-verifier.js','./progress-storage.js?v=20261003','./','./index.html','./chatgpt.html','./styles.css?v=30.4.45','./hub-daylight.css?v=30.4.38','./hub-editorial.css?v=1.1.0','./app.js?v=30.4.45','./apps.json','./versions.json','./manifest.webmanifest','./icon.svg','./icon-192.png','./icon-512.png','./apps/dc-inbox/','./apps/dc-inbox/index.html','./apps/dc-inbox/styles.css','./apps/dc-inbox/app.js','./apps/cambio/','./apps/cambio/index.html','./apps/cambio/styles.css','./apps/cambio/app.js','./apps/entrenamiento/','./apps/entrenamiento/index.html','./apps/entrenamiento/styles.css','./apps/entrenamiento/app.js','./apps/entrenamiento/data/latest.json','./apps/adri-type/','./apps/adri-type/index.html','./apps/adri-type/styles.css','./apps/adri-type/app.js','./apps/job-engine/','./apps/job-engine/index.html','./apps/job-engine/styles.css','./apps/job-engine/app.js','./apps/biblioteca/','./apps/biblioteca/index.html','./apps/biblioteca/styles.css','./apps/biblioteca/app.js','./apps/biblioteca/mode-tarea.js','./apps/biblioteca/easy-catalan.json','./apps/agents/','./apps/agents/index.html','./apps/agents/styles.css','./apps/agents/app.js'];
const CORE_RE=/\.(?:html|js|css|json|webmanifest)$/i;
function withTimeout(req,ms,init={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);return releaseFetch(req,{...init,signal:c.signal}).finally(()=>clearTimeout(t));}
async function installCore(){const c=await caches.open(CACHE);try{await releaseAll(SHELL.map(async url=>{const req=new Request(new URL(url,self.registration.scope),{cache:'reload'}),r=await withTimeout(req,10000,{cache:'reload'});if(!r||!r.ok)throw Error(`Core asset failed: ${url}`);await c.put(req,r.clone());}));}catch(e){await caches.delete(CACHE);throw e;}}
self.addEventListener('install',e=>e.waitUntil(installCore().then(()=>self.skipWaiting?.())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{await Promise.all((await caches.keys()).filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();const root=new URL(self.registration.scope).pathname;const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});clients.forEach(c=>{const u=new URL(c.url);if((u.pathname===root||u.pathname===root+'index.html')&&u.searchParams.get('hubfix')!=='30445'){u.searchParams.set('hubfix','30445');c.navigate(u.href).catch(()=>{});}});})()));
async function acceptShare(req){const fd=await req.formData(),id=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);const files=fd.getAll('files').filter(v=>v instanceof File),cache=await caches.open(PAYLOADS),base=new URL('./__dc_share/',self.registration.scope);const meta={title:fd.get('title')||'',text:fd.get('text')||'',url:fd.get('url')||'',createdAt:new Date().toISOString(),files:[]};for(let i=0;i<files.length;i++){const x=files[i],key=new URL('file/'+id+'/'+i,base).href;await cache.put(key,new Response(x,{headers:{'Content-Type':x.type||'application/octet-stream'}}));meta.files.push({name:x.name,type:x.type,size:x.size,key});}await cache.put(new URL('meta/'+id,base).href,new Response(JSON.stringify(meta),{headers:{'Content-Type':'application/json'}}));return Response.redirect(new URL('./apps/dc-inbox/?share='+encodeURIComponent(id),self.registration.scope).href,303);}
async function network(req,ms=5000){try{return await withTimeout(req,ms,{cache:'no-cache'});}catch(_){return null;}}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method==='POST'&&u.pathname.endsWith('/share-target')){e.respondWith(acceptShare(e.request));return;}if(e.request.method!=='GET'||u.origin!==location.origin||!u.pathname.startsWith(SCOPE_PATH))return;e.respondWith((async()=>{const c=await caches.open(CACHE),core=e.request.mode==='navigate'||CORE_RE.test(u.pathname);if(core){const r=await network(e.request,1800);if(r&&r.ok){await c.put(e.request,r.clone());return r;}const hit=await releaseMatch(c,e.request);if(hit)return hit;if(e.request.mode==='navigate'&&(u.pathname===SCOPE_PATH||u.pathname===SCOPE_PATH+'index.html'))return (await c.match('./index.html'))||(await c.match('./'))||Response.error();return Response.error();}const hit=await releaseMatch(c,e.request);if(hit)return hit;const r=await network(e.request,5000);if(r&&r.ok){await c.put(e.request,r.clone());return r;}return Response.error();})());});
